---
title: "Introduction"
author: "Aravind Hebbali"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r libs}
library(blorr)
library(magrittr)
```

# Bivariate Analysis

### Introduction

```{r bivar1}
blr_bivariate_analysis(hsb2, honcomp, prog)
```

## Response Distribution

```{r bivar2}
blr_segment(hsb2, honcomp, prog)
```

## Response Distribution by Multiple Segments

```{r bivar3}
blr_twoway_segment(hsb2, honcomp, prog, female)
```

## Response Distribution by Segments

#### Introduction

```{r bivar4}
blr_segment_dist(hsb2, honcomp, prog)
```

#### Plot

```{r bivar5, fig.align='center', fig.width=5, fig.height=5}
blr_segment_dist(hsb2, honcomp, prog) %>%
  plot
```

## Weight of Evidemce & Information Value

#### Introduction

```{r woe1}
blr_woe_iv(hsb2, female, honcomp)
```

#### Plot

```{r woe2, fig.align='center', fig.width=5, fig.height=5}
blr_woe_iv(hsb2, female, honcomp) %>%
  plot
```

## Regression

```{r reg1}
blr_regress(object = honcomp ~ female + read + science, data = hsb2)
```

## Model Fit Statistics

```{r mfs}
model <- glm(honcomp ~ female + read + science, data = hsb2,
             family = binomial(link = 'logit'))

blr_model_fit_stats(model)
```

## Model Validation

### Gains Table

```{r val1}
blr_gains_table(model)
```

### ROC Curve

```{r val2, fig.align='center', fig.width=7, fig.height=5}
blr_gains_table(model) %>%
  blr_roc_curve
```

### KS Chart

```{r val3, fig.align='center', fig.width=7, fig.height=5}
blr_gains_table(model) %>%
  blr_ks_chart
```

### Lorenz Curve

```{r val4, fig.align='center', fig.width=7, fig.height=5}
blr_lorenz_curve(model)
```

### Confusion Matrix

```{r val5}
blr_confusion_matrix(model, cutoff = 0.5)
```

### Hosmer Lemeshow Test

```{r val6}
blr_hosmer_lemeshow_test(model)
```


