---
title: "Model Validation"
author: "Aravind Hebbali"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model Validation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r libs}
library(blorr)
library(magrittr)
```

### Regression Model

```{r model}
model <- glm(y ~ job + housing + contact + poutcome + duration + month +
             campaign + loan + marital + education + day + balance + previous, 
             data = bank_marketing, family = binomial(link = 'logit'))
```

### Confusion Matrix

```{r val5}
blr_confusion_matrix(model, cutoff = 0.5)
```

### Hosmer Lemeshow Test

```{r val6}
blr_test_hosmer_lemeshow(model)
```


### Gains Table

```{r val1}
blr_gains_table(model)
```

### Lift Chart

```{r val7}
model %>%
	blr_gains_table() %>%
	plot()
```

### ROC Curve

```{r val2, fig.align='center', fig.width=7, fig.height=5}
model %>%
	blr_gains_table() %>%
  blr_roc_curve()
```

### KS Chart

```{r val3, fig.align='center', fig.width=7, fig.height=5}
model %>%
	blr_gains_table() %>%
  blr_ks_chart()
```

### Decile Lift Chart

```{r val9, fig.align='center', fig.width=7, fig.height=5}
model %>%
  blr_gains_table() %>%
  blr_decile_lift_chart()
```


### Capture Rate by Decile

```{r val8, fig.align='center', fig.width=7, fig.height=5}
model %>%
  blr_gains_table() %>%
  blr_decile_capture_rate()
```


### Lorenz Curve

```{r val4, fig.align='center', fig.width=7, fig.height=5}
blr_lorenz_curve(model)
```

