---
title: "Variable Selection"
author: "Aravind Hebbali"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Variable Selection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r libs}
library(blorr)
library(ggplot2)
library(magrittr)
```

### Forward Selection

#### Model

```{r mod1}
model <- glm(honcomp ~ female + read + science, data = hsb2,
  family = binomial(link = 'logit'))
```

#### Selection Summary

```{r forward1}
blr_step_aic_forward(model)
```

#### Detailed Output

```{r forward2}
blr_step_aic_forward(model, details = TRUE)
```

#### Plot

```{r forward3}
model %>%
  blr_step_aic_forward() %>%
  plot()
```

### Backward Elimination

#### Model

```{r mod2}
model <- glm(honcomp ~ female + read + science + math + prog + socst, data = hsb2, family = binomial(link = 'logit'))
```

#### Selection Summary

```{r backward1}
blr_step_aic_backward(model)
```

#### Detailed Output

```{r backward2}
blr_step_aic_backward(model, details = TRUE)
```

#### Plot

```{r backward3}
model %>%
  blr_step_aic_backward() %>%
  plot()
```

### Stepwise Selection

#### Model

```{r mod3}
model <- glm(y ~ ., data = stepwise)
```

#### Selection Summary

```{r stepwise1}
blr_step_aic_both(model)
```

#### Detailed Output

```{r stepwise2}
blr_step_aic_both(model, details = TRUE)
```

#### Plot

```{r stepwise3}
model %>%
  blr_step_aic_both() %>%
  plot()
```

